### ISSUE TITLE
IMPACT Checklist Vignette

### ISSUE THREAD

**Issue by karissawhiting** [MSKCC-Epi-Bio/gnomeR#176]
Create a vignette in {gnomeR} to guide people through IMPACT data checks with explanations and examples

- [ ] Decide what data set /samples to use.
- [ ] Create branch and Rmd document for Esther to work on during hackathon
- [ ] Karissa will add example code for the first item below using cbioportalR once we decide on example samples

**Pre Analysis Sample Checks**

- Pull clinical and genomic and compare the two to make sure all were sampled. Get list of samples to make sure there are none missing or incorrect (we can use `get_clinical_by_sample()`). Find an example of this or create one where the investigator gives you a sample with incorrect ID? 
     - In {cbioportalR} - Maybe add a more descriptive warning message of which samples were not found. 
- Duplicate patient check when multiple samples per patient - (helper function?)
- Check cancer type against Oncotree code (helper function?)(maybe add oncotree dictionary?)
- Also check sample_type (primary/mets) against clinical data. (helper function?)

**Genomic data Checks**

- Gene alias check (just write a note about why we need to do this and how gnomeR handles this) 
- Data checks between research and IMPACT samples. Send an example to Esther with current messaging to see if she things it's descriptive enough
- Any germline? remove them. Also there are blanks NA. These are likely somatic without matched pairs. Suggest that ppl do sensitivity analysis. 
- Compare TMB between research samples & IMPACT
- Something about threshold - maybe if small n do x% in either group?  
- oncoKB cancer type - maybe add note about how you need this for oncoKB annotating ?

**Maybe if you have research samples those related items are separated into a different section?**

**Comment by edrill** [comment]
Hi Karissa, I see you are getting a new sample data set together for gnomeR. Maybe makes sense to use the same one for the vignette?

**Comment by karissawhiting** [comment]
@edrill Yes, I think that makes the most sense. I am reviewing and merging the newest data example today so it will be ready for the hackathon updates tomorrow!

**Comment by karissawhiting** [comment]
@karissawhiting Review and follow up
